### ISSUE TITLE
ChatterBotGroupTriggerHandler.cls failed to Deploy

### ISSUE THREAD

**Issue by ittookten** [DouglasCAyers/salesforce-chatter-bot-groups#3]
Full Deploy message:

Status: Completed 
Deployment Complete
Failures:
classes/ChatterBotGroupTriggerHandler.cls(17,47):description, ownerId, collaborationType, groupEmail,
                                         ^
ERROR at Row:3:Column:68
No such column 'groupEmail' on entity 'CollaborationGroup'. If you are attempting to use a custom field, be sure to append the '__c' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.
classes/ChatterBotGroupTriggerHandler.cls(94,54):Variable does not exist: groupEmail
triggers/ChatterBotGroupTrigger.trigger(7,5):Invalid type: ChatterBotGroupTriggerHandler
permissionsets/Chatter_Bot_Groups_Admin.permissionset(Chatter_Bot_Groups_Admin):In field: apexClass - no ApexClass named ChatterBotGroupTriggerHandler found

**Comment by douglascayers** [comment]
Hi @ittookten,

The package assumes you have [Allow Users to post to Chatter Groups via Email](https://help.salesforce.com/articleView?id=000188545&type=1) enabled in your Chatter Settings. Enabling this will provide the `groupEmail` field that the app is querying for.

Sorry for the confusion or inconvenience.
